from pathlib import Path
p=Path('/mnt/data/j45/dashboard.html')
s=p.read_text()
css='''.wf-grid{display:grid;grid-template-columns:repeat(6,minmax(90px,1fr));gap:5px}.wf-stat{border:1px solid rgba(0,240,255,.1);padding:6px}.wf-stat span{display:block;font-size:5px;color:var(--mut)}.wf-stat b{display:block;font:700 10px Orbitron;color:var(--txt);margin-top:3px}.wf-toolbar{display:flex;gap:5px;flex-wrap:wrap;margin-bottom:7px}.wf-toolbar input,.wf-toolbar select{background:#07101a;border:1px solid rgba(0,240,255,.15);color:#9bb0bf;padding:5px;font:6px JetBrains Mono}.wf-toolbar button{background:#07101a;border:1px solid rgba(0,240,255,.2);color:var(--c);padding:5px 8px;font:700 6px JetBrains Mono;cursor:pointer}.wf-table{width:100%;border-collapse:collapse;font-size:6px}.wf-table td,.wf-table th{padding:4px;border-bottom:1px solid rgba(0,240,255,.06);text-align:right}.wf-table th{color:var(--mut);font-weight:500}.wf-table td:first-child,.wf-table th:first-child{text-align:left}.wf-good{color:var(--ok)!important}.wf-warn{color:var(--g)!important}.wf-bad{color:var(--r)!important}.wf-pill{display:inline-block;border:1px solid rgba(0,240,255,.14);padding:4px 6px;margin:2px;color:#8fa5b4}.wf-note{font-size:6px;color:var(--mut);line-height:1.6}@media(max-width:900px){.wf-grid{grid-template-columns:repeat(3,1fr)}}'''
s=s.replace('</style>',css+'</style>',1)
marker='  <section class="ic-card ic-wide eventbus-card">'
card='''  <section class="ic-card ic-wide"><h3>JARVIS 4.5 // WALK-FORWARD / OOS / MONTE-CARLO INTELLIGENCE</h3><div class="wf-toolbar"><input id="wfFrom" type="datetime-local"><input id="wfTo" type="datetime-local"><select id="wfSymbol"><option value="">ALL SYMBOLS</option></select><input id="wfTrain" type="number" value="120" min="20" max="1000"><input id="wfTest" type="number" value="40" min="10" max="500"><input id="wfStep" type="number" value="40" min="1" max="500"><button onclick="loadBacktestIntelligence()">RUN OOS ANALYSIS</button></div><div class="wf-grid"><div class="wf-stat"><span>DATA EVENTS</span><b id="wfEvents">—</b></div><div class="wf-stat"><span>PRICE POINTS</span><b id="wfPoints">—</b></div><div class="wf-stat"><span>WF WINDOWS</span><b id="wfWindows">—</b></div><div class="wf-stat"><span>OOS RETURN</span><b id="wfOosReturn">—</b></div><div class="wf-stat"><span>OOS SHARPE</span><b id="wfOosSharpe">—</b></div><div class="wf-stat"><span>OOS MAX DD</span><b id="wfOosDD">—</b></div><div class="wf-stat"><span>OOS WIN RATE</span><b id="wfOosWin">—</b></div><div class="wf-stat"><span>TRAIN→OOS DEG.</span><b id="wfDeg">—</b></div><div class="wf-stat"><span>MC P05 RETURN</span><b id="wfMcP05">—</b></div><div class="wf-stat"><span>MC P50 RETURN</span><b id="wfMcP50">—</b></div><div class="wf-stat"><span>MC P95 RETURN</span><b id="wfMcP95">—</b></div><div class="wf-stat"><span>GOVERNANCE</span><b id="wfGov">LOCKED</b></div></div><div style="margin-top:8px"><span class="wf-pill" id="wfActions">ACTIONS —</span><span class="wf-pill" id="wfRange">RANGE —</span></div><div style="margin-top:8px;max-height:180px;overflow:auto"><table class="wf-table"><thead><tr><th>WINDOW</th><th>TRAIN SHARPE</th><th>TEST/OOS SHARPE</th><th>TEST RETURN</th><th>TEST WIN%</th><th>TEST MAX DD</th></tr></thead><tbody id="wfWindowsTable"><tr><td colspan="6" class="wf-note">RUN ANALYSIS TO POPULATE WALK-FORWARD WINDOWS.</td></tr></tbody></table></div><div class="wf-note" style="margin-top:7px">READ-ONLY analytics over recorded market-data events. Purge/embargo are chronological leakage controls. Monte-Carlo resamples observed returns; it is not a guarantee of future performance. Live execution and automatic model promotion remain locked.</div></section>'''
s=s.replace(marker,card+'\n'+marker,1)
# insert JS before setInterval intelligence
needle="setInterval(()=>{if($('intelConsole')?.classList.contains('open')){loadIntelligence();"
js=r'''
function localDateTimeValue45(ts){const d=new Date(ts-Date.getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
function initBacktest45(){const now=Date.now();if($('wfFrom')&&!$('wfFrom').value)$('wfFrom').value=localDateTimeValue45(now-7*86400000);if($('wfTo')&&!$('wfTo').value)$('wfTo').value=localDateTimeValue45(now);const sel=$('wfSymbol');if(sel){for(const c of [...new Set((scanRows||[]).map(x=>x.symbol).filter(Boolean))])if(![...sel.options].some(o=>o.value===c)){const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o)}}}
function renderBacktest45(d){const o=d.oos||{}, ins=d.inSample||{}, mc=d.monteCarlo?.summary||{};txt('wfEvents',d.dataset?.events??0);txt('wfPoints',d.dataset?.pricePoints??0);txt('wfWindows',d.windows?.length??0);txt('wfOosReturn',Number(o.totalReturn||0).toFixed(2)+'%');txt('wfOosSharpe',Number(o.sharpe||0).toFixed(2));txt('wfOosDD',Number(o.maxDrawdown||0).toFixed(2)+'%');txt('wfOosWin',Number(o.winRate||0).toFixed(1)+'%');txt('wfDeg',Number(d.degradation||0).toFixed(2));txt('wfMcP05',Number(mc.returnPct?.p05||0).toFixed(2)+'%');txt('wfMcP50',Number(mc.returnPct?.p50||0).toFixed(2)+'%');txt('wfMcP95',Number(mc.returnPct?.p95||0).toFixed(2)+'%');txt('wfGov',d.governance?.modelPromotionAllowed?'OPEN':'LOCKED');txt('wfRange',new Date(d.range?.from||Date.now()).toLocaleDateString('de-DE')+' → '+new Date(d.range?.to||Date.now()).toLocaleDateString('de-DE'));txt('wfActions','ACTIONS '+Object.entries(d.actions||{}).map(([k,v])=>k+':'+v).join(' · '));const tb=$('wfWindowsTable');if(tb)tb.innerHTML=(d.windows||[]).map(w=>'<tr><td>#'+w.index+'</td><td>'+Number(w.train.sharpe||0).toFixed(2)+'</td><td class="'+(w.test.sharpe>=0?'wf-good':'wf-bad')+'">'+Number(w.test.sharpe||0).toFixed(2)+'</td><td>'+Number(w.test.totalReturn||0).toFixed(2)+'%</td><td>'+Number(w.test.winRate||0).toFixed(1)+'%</td><td>'+Number(w.test.maxDrawdown||0).toFixed(2)+'%</td></tr>').join('')||'<tr><td colspan="6" class="wf-note">NOT ENOUGH RECORDED DATA FOR THE REQUESTED WINDOWS.</td></tr>'}
async function loadBacktestIntelligence(){try{initBacktest45();const from=Date.parse($('wfFrom')?.value||''),to=Date.parse($('wfTo')?.value||'');const q=new URLSearchParams({from:String(Number.isFinite(from)?from:Date.now()-7*86400000),to:String(Number.isFinite(to)?to:Date.now()),trainSize:$('wfTrain')?.value||120,testSize:$('wfTest')?.value||40,stepSize:$('wfStep')?.value||40});const sym=$('wfSymbol')?.value||'';if(sym)q.set('symbol',sym);const r=await fetch('/api/dashboard/backtest-intelligence?'+q.toString());if(!r.ok)throw new Error('HTTP '+r.status);renderBacktest45(await r.json())}catch(e){txt('wfGov','ERROR');console.error('[JARVIS 4.5]',e)}}

'''
s=s.replace(needle,js+needle,1)
# initialize and update symbol options
s=s.replace('renderTabs();load();loadScan();loadMarketOverview();loadAgents();', 'renderTabs();initBacktest45();load();loadScan();loadMarketOverview();loadAgents();loadBacktestIntelligence();')
p.write_text(s)
