'use strict';

/**
 * // IMPROVED: Central configuration and filter registry.
 */
const STRATEGY_PROFILES = {
  loose: {
    ALLOW_COUNTER_BTC_TREND: true, REQUIRE_4H_TREND: false, ADX_MIN: 15,
    RSI_LONG_MIN: 40, RSI_LONG_MAX: 75, RSI_SHORT_MIN: 25, RSI_SHORT_MAX: 60,
    MIN_RELATIVE_VOLUME: 0.8, BOS_LOOKBACK: 4, TREND_EMA_FAST_15M: 20, TREND_EMA_SLOW_15M: 50
  },
  strict: {
    ALLOW_COUNTER_BTC_TREND: false, REQUIRE_4H_TREND: true, ADX_MIN: 20,
    RSI_LONG_MIN: 48, RSI_LONG_MAX: 68, RSI_SHORT_MIN: 32, RSI_SHORT_MAX: 52,
    MIN_RELATIVE_VOLUME: 1.2, BOS_LOOKBACK: 10, TREND_EMA_FAST_15M: 20, TREND_EMA_SLOW_15M: 50
  }
};

function num(env, key, fallback) {
  const v = env[key];
  return v === undefined ? fallback : Number(v);
}
function int(env, key, fallback) {
  const v = env[key];
  return v === undefined ? fallback : parseInt(v, 10);
}
function bool(env, key, fallback) {
  if (env[key] === undefined) return fallback;
  return env[key] !== 'false';
}

function buildConfig(env = process.env) {
  const profileName = String(env.STRATEGY_PROFILE || 'strict').toLowerCase();
  const profile = STRATEGY_PROFILES[profileName] || STRATEGY_PROFILES.strict;
  const cfg = {
    PORT: int(env,'PORT',10000),
    API_BIND_HOST: env.API_BIND_HOST || '0.0.0.0',
    API_KEY: env.API_KEY || '',
    CAPITAL_USD: num(env,'CAPITAL_USD',10000), RISK_PERCENT: num(env,'RISK_PERCENT',0.75),
    TOP_COIN_LIMIT: int(env,'TOP_COIN_LIMIT',150), MAX_SIGNALS_PER_SCAN: int(env,'MAX_SIGNALS_PER_SCAN',5),
    MAX_CONCURRENT_TRADES: int(env,'MAX_CONCURRENT_TRADES',3), MAX_DAILY_LOSS_USD: num(env,'MAX_DAILY_LOSS_USD',250),
    MAX_FUNDING_RATE: num(env,'MAX_FUNDING_RATE',0.0005), MIN_FUNDING_RATE: num(env,'MIN_FUNDING_RATE',-0.0005),
    ALLOW_COUNTER_BTC_TREND: bool(env,'ALLOW_COUNTER_BTC_TREND',profile.ALLOW_COUNTER_BTC_TREND),
    REQUIRE_4H_TREND: bool(env,'REQUIRE_4H_TREND',profile.REQUIRE_4H_TREND),
    ADX_MIN: num(env,'ADX_MIN',profile.ADX_MIN),
    RSI_LONG_MIN: num(env,'RSI_LONG_MIN',profile.RSI_LONG_MIN), RSI_LONG_MAX: num(env,'RSI_LONG_MAX',profile.RSI_LONG_MAX),
    RSI_SHORT_MIN: num(env,'RSI_SHORT_MIN',profile.RSI_SHORT_MIN), RSI_SHORT_MAX: num(env,'RSI_SHORT_MAX',profile.RSI_SHORT_MAX),
    MIN_RELATIVE_VOLUME: num(env,'MIN_RELATIVE_VOLUME',profile.MIN_RELATIVE_VOLUME),
    BOS_LOOKBACK: int(env,'BOS_LOOKBACK',profile.BOS_LOOKBACK),
    TREND_EMA_FAST_15M: int(env,'TREND_EMA_FAST_15M',profile.TREND_EMA_FAST_15M),
    TREND_EMA_SLOW_15M: int(env,'TREND_EMA_SLOW_15M',profile.TREND_EMA_SLOW_15M),
    ATR_STOP_MULT:num(env,'ATR_STOP_MULT',2.3), TP1_MULT:num(env,'TP1_MULT',1.3), TP2_MULT:num(env,'TP2_MULT',2.5),
    MAX_HOLD_HOURS:num(env,'MAX_HOLD_HOURS',4), ABSOLUTE_MAX_HOLD_HOURS:num(env,'ABSOLUTE_MAX_HOLD_HOURS',24),
    DYNAMIC_TIME_STOP_MAX_EXTENSION_HOURS:num(env,'DYNAMIC_TIME_STOP_MAX_EXTENSION_HOURS',2),
    DYNAMIC_TIME_STOP_EXTENSION_STEP_HOURS:num(env,'DYNAMIC_TIME_STOP_EXTENSION_STEP_HOURS',1),
    DYNAMIC_TIME_STOP_MIN_TREND_SCORE:num(env,'DYNAMIC_TIME_STOP_MIN_TREND_SCORE',0.56),
    TIMESFM_ENABLED:bool(env,'TIMESFM_ENABLED',false), TIMESFM_WEIGHT:num(env,'TIMESFM_WEIGHT',0.30),
    TIMESFM_MODEL:env.TIMESFM_MODEL||'google/timesfm-2.5-200m-transformers', TIMESFM_TIMEOUT_MS:int(env,'TIMESFM_TIMEOUT_MS',15000),
    MAX_SAME_DIRECTION:int(env,'MAX_SAME_DIRECTION',2), TRAILING_STOP_ENABLED:bool(env,'TRAILING_STOP_ENABLED',true),
    TRAILING_ATR_MULT:num(env,'TRAILING_ATR_MULT',2.2), DYNAMIC_TRAILING_ATR:bool(env,'DYNAMIC_TRAILING_ATR',true),
    FAST_TRACK_INTERVAL_SECONDS:int(env,'FAST_TRACK_INTERVAL_SECONDS',60), TICKER_BATCH_SIZE:int(env,'TICKER_BATCH_SIZE',10),
    SLIPPAGE_PERCENT:num(env,'SLIPPAGE_PERCENT',0.10), FEE_PERCENT:num(env,'FEE_PERCENT',0.1), TP1_CLOSE_PERCENT:num(env,'TP1_CLOSE_PERCENT',60),
    ENABLE_SHORT_SIGNALS:bool(env,'ENABLE_SHORT_SIGNALS',true), MAX_EXPOSURE_RATIO:num(env,'MAX_EXPOSURE_RATIO',0.6),
    SCAN_CONCURRENCY:int(env,'SCAN_CONCURRENCY',10), KUCOIN_MARKET_DATA_TIMEOUT_MS:int(env,'KUCOIN_MARKET_DATA_TIMEOUT_MS',7000), KUCOIN_MARKET_DATA_RETRIES:int(env,'KUCOIN_MARKET_DATA_RETRIES',0), KUCOIN_CIRCUIT_THRESHOLD:int(env,'KUCOIN_CIRCUIT_THRESHOLD',3), KUCOIN_CIRCUIT_COOLDOWN_MS:int(env,'KUCOIN_CIRCUIT_COOLDOWN_MS',300000), KUCOIN_HALF_OPEN_PROBE_TIMEOUT_MS:int(env,'KUCOIN_HALF_OPEN_PROBE_TIMEOUT_MS',7000), KUCOIN_KLINE_CACHE_TTL_MS:int(env,'KUCOIN_KLINE_CACHE_TTL_MS',3000), LEVERAGE:int(env,'LEVERAGE',3), MARGIN_MODE:String(env.MARGIN_MODE||'ISOLATED').toUpperCase(),
    FUNDING_INTERVAL_HOURS:num(env,'FUNDING_INTERVAL_HOURS',8),
    MAX_KLINES_CACHE_SIZE:int(env,'MAX_KLINES_CACHE_SIZE',200), CACHE_CLEANUP_MINUTES:int(env,'CACHE_CLEANUP_MINUTES',5),
    MAX_DRAWDOWN_PERCENT:num(env,'MAX_DRAWDOWN_PERCENT',25), DAILY_PROFIT_TARGET:num(env,'DAILY_PROFIT_TARGET',500),
    MAX_WEEKLY_DRAWDOWN_PERCENT:num(env,'MAX_WEEKLY_DRAWDOWN_PERCENT',10), MAX_CONSECUTIVE_LOSSES:int(env,'MAX_CONSECUTIVE_LOSSES',3),
    ENABLE_ADAPTIVE_PARAMS:bool(env,'ENABLE_ADAPTIVE_PARAMS',true), ENABLE_KELLY_SIZING:bool(env,'ENABLE_KELLY_SIZING',true),
    ENABLE_ORDERBOOK_ANALYSIS:bool(env,'ENABLE_ORDERBOOK_ANALYSIS',true), ENABLE_CORRELATION_LIMITS:bool(env,'ENABLE_CORRELATION_LIMITS',true),
    ENABLE_MULTI_TF_DERIVATION:bool(env,'ENABLE_MULTI_TF_DERIVATION',true), ENABLE_TIME_FILTER:bool(env,'ENABLE_TIME_FILTER',true),
    ORDERBOOK_DEPTH_LEVELS:int(env,'ORDERBOOK_DEPTH_LEVELS',10), MAX_SPREAD_PERCENT:num(env,'MAX_SPREAD_PERCENT',0.15),
    RISK_GOVERNOR_MAX_SPREAD_PCT:num(env,'RISK_GOVERNOR_MAX_SPREAD_PCT',0.15),
    RISK_GOVERNOR_MAX_SLIPPAGE_PCT:num(env,'RISK_GOVERNOR_MAX_SLIPPAGE_PCT',0.20),
    RISK_GOVERNOR_MAX_MARKET_DATA_AGE_MS:int(env,'RISK_GOVERNOR_MAX_MARKET_DATA_AGE_MS',5000),
    RISK_GOVERNOR_MAX_EXCHANGE_LATENCY_MS:int(env,'RISK_GOVERNOR_MAX_EXCHANGE_LATENCY_MS',3000),
    RISK_GOVERNOR_MAX_POSITION_NOTIONAL_USD:num(env,'RISK_GOVERNOR_MAX_POSITION_NOTIONAL_USD',Infinity),
    RISK_GOVERNOR_MAX_ORDER_NOTIONAL_USD:num(env,'RISK_GOVERNOR_MAX_ORDER_NOTIONAL_USD',Infinity),
    RISK_GOVERNOR_MAX_VOLATILITY_PCT:num(env,'RISK_GOVERNOR_MAX_VOLATILITY_PCT',12),
    RISK_GOVERNOR_MAX_CONCENTRATION_PCT:num(env,'RISK_GOVERNOR_MAX_CONCENTRATION_PCT',60),
    RISK_GOVERNOR_MAX_CORRELATION_PCT:num(env,'RISK_GOVERNOR_MAX_CORRELATION_PCT',90),
    RISK_GOVERNOR_REDUCED_DD_RATIO:num(env,'RISK_GOVERNOR_REDUCED_DD_RATIO',0.75),
    RISK_GOVERNOR_REDUCED_DAILY_LOSS_RATIO:num(env,'RISK_GOVERNOR_REDUCED_DAILY_LOSS_RATIO',0.75),
    RISK_GOVERNOR_REDUCED_EXPOSURE_RATIO:num(env,'RISK_GOVERNOR_REDUCED_EXPOSURE_RATIO',0.85),
    RISK_GOVERNOR_EMERGENCY_DD_MULTIPLIER:num(env,'RISK_GOVERNOR_EMERGENCY_DD_MULTIPLIER',1.25),
    RISK_GOVERNOR_EMERGENCY_DAILY_LOSS_MULTIPLIER:num(env,'RISK_GOVERNOR_EMERGENCY_DAILY_LOSS_MULTIPLIER',1.25),
    MAX_CHOP_INDEX:num(env,'MAX_CHOP_INDEX',61.8), MIN_HURST_EXPONENT:num(env,'MIN_HURST_EXPONENT',0.52),
    MIN_GATE_SCORE:num(env,'MIN_GATE_SCORE',55), MIN_RRR:num(env,'MIN_RRR',1.5),
    ML_ENABLED:bool(env,'ML_ENABLED',true), ML_MIN_TRAINING_SAMPLES:int(env,'ML_MIN_TRAINING_SAMPLES',40),
    ML_MAX_TRAINING_SAMPLES:int(env,'ML_MAX_TRAINING_SAMPLES',2000), ML_MIN_PREDICTION_PROBABILITY:num(env,'ML_MIN_PREDICTION_PROBABILITY',0.55),
    ML_STRONG_SIGNAL_PROBABILITY:num(env,'ML_STRONG_SIGNAL_PROBABILITY',0.70), ML_RETRAIN_HOURS:num(env,'ML_RETRAIN_HOURS',6),
    ML_EPOCHS:int(env,'ML_EPOCHS',80), ML_BATCH_SIZE:int(env,'ML_BATCH_SIZE',32),
    ML_HYPERPARAM_SEARCH_EVERY:int(env,'ML_HYPERPARAM_SEARCH_EVERY',5),
    KLINES_SCAN_LIMIT:int(env,'KLINES_SCAN_LIMIT',60),
    TELEGRAM_QUEUE_MAX:int(env,'TELEGRAM_QUEUE_MAX',100),
    DB_BULK_QUEUE_MAX:int(env,'DB_BULK_QUEUE_MAX',500), DB_BULK_MAX_RETRIES:int(env,'DB_BULK_MAX_RETRIES',3),
    // FIX: Render zero-downtime deployments use a coordinated MongoDB lock handoff.
    LOCK_ACQUIRE_RETRIES:int(env,'LOCK_ACQUIRE_RETRIES',30), LOCK_ACQUIRE_RETRY_DELAY_MS:int(env,'LOCK_ACQUIRE_RETRY_DELAY_MS',2000),
    LOCK_STALE_AFTER_MS:int(env,'LOCK_STALE_AFTER_MS',300000), LOCK_HEARTBEAT_INTERVAL_MS:int(env,'LOCK_HEARTBEAT_INTERVAL_MS',2000),
    LOCK_HANDOFF_ENABLED:bool(env,'LOCK_HANDOFF_ENABLED',true),
    MONGODB_POOL_SIZE:int(env,'MONGODB_POOL_SIZE',10), DB_BULK_INTERVAL_MS:int(env,'DB_BULK_INTERVAL_MS',5000),
    TELEGRAM_BOT_TOKEN:env.TELEGRAM_BOT_TOKEN||'', TELEGRAM_CHAT_ID:env.TELEGRAM_CHAT_ID||'', MONGODB_URI:env.MONGODB_URI||'',
    DQN_ENABLED:true,
    ENABLE_ADVANCED_MTF: bool(env,'ENABLE_ADVANCED_MTF',false),
    ADVANCED_MTF_MAX_SYMBOLS:int(env,'ADVANCED_MTF_MAX_SYMBOLS',20),
    CVD_ENABLED:bool(env,'CVD_ENABLED',true),
    CVD_LOOKBACK:int(env,'CVD_LOOKBACK',20),
    VWMACD_FAST:int(env,'VWMACD_FAST',12), VWMACD_SLOW:int(env,'VWMACD_SLOW',26), VWMACD_SIGNAL:int(env,'VWMACD_SIGNAL',9),
    ICHIMOKU_CONVERSION:int(env,'ICHIMOKU_CONVERSION',9), ICHIMOKU_BASE:int(env,'ICHIMOKU_BASE',26), ICHIMOKU_SPAN_B:int(env,'ICHIMOKU_SPAN_B',52),
    FIB_LOOKBACK:int(env,'FIB_LOOKBACK',120), FIB_ZONE_TOLERANCE:num(env,'FIB_ZONE_TOLERANCE',0.004),
    EXECUTION_ENABLED:bool(env,'EXECUTION_ENABLED',false), DRY_RUN:bool(env,'DRY_RUN',true), KILL_SWITCH_ENABLED:bool(env,'KILL_SWITCH_ENABLED',true),
    KUCOIN_API_KEY:env.KUCOIN_API_KEY||'', KUCOIN_API_SECRET:env.KUCOIN_API_SECRET||'', KUCOIN_API_PASSPHRASE:env.KUCOIN_API_PASSPHRASE||'',
    DQN_REPLAY_ALPHA:num(env,'DQN_REPLAY_ALPHA',0.6), DQN_REPLAY_BETA:num(env,'DQN_REPLAY_BETA',0.4), DQN_REPLAY_CAPACITY:int(env,'DQN_REPLAY_CAPACITY',10000),
    DRIFT_WINDOW:int(env,'DRIFT_WINDOW',200), DRIFT_THRESHOLD:num(env,'DRIFT_THRESHOLD',0.35),
    AI_AGENTS_ENABLED:bool(env,'AI_AGENTS_ENABLED',true), AI_AGENT_MIN_SCORE:num(env,'AI_AGENT_MIN_SCORE',0.58),
    DATA_RECOVERY_RETRIES:int(env,'DATA_RECOVERY_RETRIES',3), DATA_RECOVERY_BACKOFF_MS:int(env,'DATA_RECOVERY_BACKOFF_MS',500), DATA_RECOVERY_LIMITS:env.DATA_RECOVERY_LIMITS||'100,200,300',
    AI_LLM_ENABLED:bool(env,'AI_LLM_ENABLED',false), GEMINI_API_KEY:env.GEMINI_API_KEY||'',
    GEMINI_MODEL:env.GEMINI_MODEL||'gemini-3.7-flash', AI_LLM_COOLDOWN_MS:int(env,'AI_LLM_COOLDOWN_MS',60000)
  };
  return cfg;
}

function validateConfig(config) {
  const numeric = ['PORT','CAPITAL_USD','RISK_PERCENT','MAX_CONCURRENT_TRADES','MAX_DAILY_LOSS_USD','ADX_MIN',
    'RSI_LONG_MIN','RSI_LONG_MAX','RSI_SHORT_MIN','RSI_SHORT_MAX','MIN_RELATIVE_VOLUME','BOS_LOOKBACK',
    'ATR_STOP_MULT','TP1_MULT','TP2_MULT','MAX_EXPOSURE_RATIO','MAX_DRAWDOWN_PERCENT','MIN_GATE_SCORE',
    'ML_MIN_TRAINING_SAMPLES','ML_EPOCHS','ML_BATCH_SIZE','KLINES_SCAN_LIMIT'];
  for (const k of numeric) if (!Number.isFinite(Number(config[k]))) throw new Error(`[CONFIG ERROR] ${k} ungültig.`);
  if (!['ISOLATED','CROSS'].includes(config.MARGIN_MODE)) throw new Error('[CONFIG ERROR] MARGIN_MODE ungültig');
  if (config.KLINES_SCAN_LIMIT < 35) throw new Error('[CONFIG ERROR] KLINES_SCAN_LIMIT muss >= 35 für MACD sein.');
  if (config.TELEGRAM_QUEUE_MAX < 1 || config.DB_BULK_QUEUE_MAX < 1) throw new Error('[CONFIG ERROR] Queue-Limits müssen > 0 sein.');
  return config;
}

const FILTER_REGISTRY = {
  hurst:{configKey:'MIN_HURST_EXPONENT',name:'Hurst Exponent',default:0.52,type:'numeric',step:0.02},
  adx:{configKey:'ADX_MIN',name:'ADX Minimum',default:20,type:'numeric',step:2},
  bos:{configKey:'BOS_LOOKBACK',name:'BOS Lookback',default:10,type:'numeric',step:2},
  relvol:{configKey:'MIN_RELATIVE_VOLUME',name:'Rel. Volumen',default:1.2,type:'numeric',step:0.1},
  chop:{configKey:'MAX_CHOP_INDEX',name:'Max Chop Index',default:61.8,type:'numeric',step:2},
  rsi_long_min:{configKey:'RSI_LONG_MIN',name:'RSI Long Min',default:48,type:'numeric',step:2},
  rsi_short_max:{configKey:'RSI_SHORT_MAX',name:'RSI Short Max',default:52,type:'numeric',step:2},
  trend4h:{configKey:'REQUIRE_4H_TREND',name:'4H Trend-Filter',default:true,type:'boolean'},
  btctrend:{configKey:'ALLOW_COUNTER_BTC_TREND',name:'Gegen-BTC-Trend',default:false,type:'boolean'},
  timetrend:{configKey:'ENABLE_TIME_FILTER',name:'Time-based Learning Filter',default:true,type:'boolean'},
  pocvwap:{configKey:null,name:'POC/VWAP-Lage',default:true,type:'boolean'},
  macd:{configKey:null,name:'MACD-Ausrichtung',default:true,type:'boolean'}
};

function createFilterState() {
  return Object.fromEntries(Object.keys(FILTER_REGISTRY).map(k => [k,{enabled:true}]));
}

module.exports = { STRATEGY_PROFILES, buildConfig, validateConfig, FILTER_REGISTRY, createFilterState };
