const assert=require('assert');
const fs=require('fs'), os=require('os'), path=require('path');
const ExecutionJournal=require('../execution-journal');
const ExecutionReplayEngine=require('../execution-replay-engine');
const Checkpoint=require('../state-checkpoint-manager');
const Suite=require('../replay-validation-suite');
const Crash=require('../crash-recovery-test-runner');

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'b13-'));
const journal=new ExecutionJournal({dir,clock:()=>1700000000000});
journal.append({type:'SIGNAL',signalId:'s1',symbol:'BTCUSDT'});
journal.append({type:'ORDER',orderId:'o1',symbol:'BTCUSDT'});
journal.append({type:'FILL',fillId:'f1',orderId:'o1',symbol:'BTCUSDT',side:'BUY',qty:1,price:100});
journal.append({type:'CANDLE',symbol:'BTCUSDT',open:100,high:105,low:99,close:103});
journal.append({type:'SL',symbol:'BTCUSDT'});
const day='2023-11-14';
const events=journal.read(day);
assert.strictEqual(events.length,5);
assert.strictEqual(journal.verify(day).ok,true);
const replay=new ExecutionReplayEngine({dir});
const state=replay.replayDay(day);
assert.strictEqual(Object.keys(state.positions).length,0);
assert.strictEqual(state.fills.length,1);
assert.strictEqual(Suite.duplicateFills(events).length,0);
assert.deepStrictEqual(Suite.missingEvents(events),[]);
const cp=new Checkpoint({file:path.join(dir,'latest.json')});
cp.saveVersioned(state,1,{sequence:events.at(-1).seq,eventHash:events.at(-1).hash});
assert.ok(cp.load());
const crash=Crash.run({events,liveState:state,replayedState:state});
assert.strictEqual(crash.passed,true);
console.log('B13 tests: OK');
